export const example = [
  {
    'Nama Lengkap': 'Michael 1',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37002,
    Role: 'SISWA',
    Username: 'michael001',
    Password: 'michael123',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'MALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'O',
    Kewarganegaraan: 'INDONESIA',
  },
  {
    'Nama Lengkap': 'Michael 2',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37003,
    Role: 'SISWA',
    Username: 'michael002',
    Password: 'michael124',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'MALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'B',
  },
  {
    'Nama Lengkap': 'Michael 3',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37004,
    Role: 'SISWA',
    Username: 'michael003',
    Password: 'michael125',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'MALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'O',
  },
  {
    'Nama Lengkap': 'Michael 4',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37005,
    Role: 'SISWA',
    Username: 'michael004',
    Password: 'michael126',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'MALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'A',
  },
  {
    'Nama Lengkap': 'Michael 5',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37006,
    Role: 'SISWA',
    Username: 'michael005',
    Password: 'michael127',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'FEMALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'O',
  },
  {
    'Nama Lengkap': 'Michael 6',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37007,
    Role: 'SISWA',
    Username: 'michael006',
    Password: 'michael128',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'MALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'O',
  },
  {
    'Nama Lengkap': 'Michael 7',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37008,
    Role: 'SISWA',
    Username: 'michael007',
    Password: 'michael129',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'MALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'AB',
  },
  {
    'Nama Lengkap': 'Michael 8',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37009,
    Role: 'SISWA',
    Username: 'michael008',
    Password: 'michael130',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'MALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'O',
  },
  {
    'Nama Lengkap': 'Michael 9',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37010,
    Role: 'SISWA',
    Username: 'michael009',
    Password: 'michael131',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'MALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'O',
  },
  {
    'Nama Lengkap': 'Michael 10',
    'Tempat Lahir': 'Surabaya',
    'Tanggal Lahir': 37011,
    Role: 'SISWA',
    Username: 'michael010',
    Password: 'michael132',
    Email: 'michael3142@gmail.com',
    'Jenis Kelamin': 'MALE',
    Alamat: 'Jl. Jalan',
    'Gol Darah': 'O',
  },
]
